version: "3.9"
services:
  api:
    build: ./mock-api
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=
    ports:
      - "5173:80"
    depends_on:
      - api
